name: rsdk-setup
description: rsdk setup Action
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: RadxaOS-SDK/rsdk
        submodules: recursive
    - name: Enable KVM group perms
      shell: bash
      run: |
        if [[ -c /dev/kvm ]]; then
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
        else
          echo "/dev/kvm not found. It may take extra time to deploy rootfs to image."
        fi
    - name: Set up QEMU Emulation
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
    - name: rsdk-welcome
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: |
          set -euo pipefail
          src/bin/rsdk welcome
