[book]
authors = ["Radxa Limited"]
language = "en"
src = "docs"
title = "rsdk"

[build]
extra-watch-dirs = ["po"]

[output.linkcheck2]

[output.html]
git-repository-url = "https://github.com/RadxaOS-SDK/rsdk/tree/main"
edit-url-template = "https://github.com/RadxaOS-SDK/rsdk/edit/main/{path}"
additional-css = [
    "./theme/css/language-picker.css",
]

[preprocessor.gettext]
after = ["links"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.cmdrun]
