#!/usr/bin/env bash

cat <<EOF

██████╗ ███████╗██████╗ ██╗  ██╗
██╔══██╗██╔════╝██╔══██╗██║ ██╔╝
██████╔╝███████╗██║  ██║█████╔╝ 
██╔══██╗╚════██║██║  ██║██╔═██╗ 
██║  ██║███████║██████╔╝██║  ██╗
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═╝  ╚═╝
RadxaOS Software Development Kit

${1:-Please run \`rsdk help\` view the user guide.}
EOF
