#!/usr/bin/env bash

rsdk-help-rsdk() {
	cat <<EOF
rsdk
====

Supported subcommands:
$("$SCRIPT_DIR/../../bin/rsdk" config completions.supported_subcommands)
EOF
}

rsdk-help-build() {
	cat <<EOF
rsdk-${FUNCNAME[0]##rsdk-help-}
====

## Command usage

    $ rsdk build <options> [product] <suite> <edition>

## Options

    --no-cache
        Do not use cached build artifacts. This will result in rootfs rebuild.
    --no-efi
        Do not create EFI partition in the generated image.
    -d | --debug
        Enable debug output. This will also build rootfs into a folder for easier
        examination.
    -T | --test-repo
        Build using Radxa APT test archives.
    -m | --mirror [mirror_url]
        Specify custom Debian / Ubuntu archive mirror URL.
    -M [mirror_url]
        Specify custom non-Debian non-Ubuntu archive mirror URL. This mirror should
        serve both Radxa archives as well as any other 3rd party archives.

        The following archives will use this mirror:
$(find "$SCRIPT_DIR/../../../externals/keyrings/" -maxdepth 1 -mindepth 1 -type d ! -name debian -a ! -name ubuntu -printf "            %f\n")
    -i | --image-name [image_name]
        Set the system image name. (Default: $("$SCRIPT_DIR/../../bin/rsdk" config build.default_image_name))
    -h | --help
        Show this message.
EOF
}

main() {
	local SCRIPT_DIR
	SCRIPT_DIR="$(dirname "$(realpath "$0")")"
	# shellcheck source=src/lib/rsdk/utils.sh
	source "$SCRIPT_DIR/../../lib/rsdk/utils.sh"

	local subcommand="${1:-rsdk}"
	shift || true
	"rsdk-help-$subcommand" "$@"
}

main "$@"
