#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
# shellcheck source=src/lib/rsdk/utils.sh
source "$SCRIPT_DIR/../../lib/rsdk/utils.sh"

DEB_ARCHIVE="rsdk-local"
DEB_SOURCE="$(realpath "$SCRIPT_DIR/../../debs")"

aptly publish drop -force-drop "$DEB_ARCHIVE" "$DEB_ARCHIVE" || true
aptly repo drop -force "$DEB_ARCHIVE" || true
aptly db cleanup

DEB_PACKAGES=("$DEB_SOURCE"/*.deb)

if ((${#DEB_PACKAGES[@]} == 0)); then
	echo "No packages were found in $DEB_SOURCE." >&2
	echo "Local package archive will not be created." >&2
	exit "$EXIT_FILE_NOT_EXIST"
fi

aptly repo create -distribution="$DEB_ARCHIVE" "$DEB_ARCHIVE"
aptly repo add "$DEB_ARCHIVE" "$DEB_SOURCE"
aptly publish repo -skip-signing "$DEB_ARCHIVE" "$DEB_ARCHIVE"
