#!/usr/bin/env bash

main() {
	local SCRIPT_DIR
	# shellcheck disable=SC2034
	SCRIPT_DIR="$(dirname "$(realpath "$0")")"

	cat <<EOF

██████╗ ███████╗██████╗ ██╗  ██╗
██╔══██╗██╔════╝██╔══██╗██║ ██╔╝
██████╔╝███████╗██║  ██║█████╔╝ 
██╔══██╗╚════██║██║  ██║██╔═██╗ 
██║  ██║███████║██████╔╝██║  ██╗
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═╝  ╚═╝
RadxaOS Software Development Kit

${1:-Please run \`rsdk help\` view the user guide.}
EOF
}

main "$@"
