#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
# shellcheck source=src/lib/rsdk/utils.sh
source "$SCRIPT_DIR/../../lib/rsdk/utils.sh"

if (($# < 2)); then
	error "$EXIT_TOO_FEW_ARGUMENTS"
fi

IMAGE="$1"
BLOCKDEV="$2"

if [[ ! -f $IMAGE ]]; then
	error "$EXIT_FILE_NOT_EXIST" "$IMAGE"
elif [[ ! -b $BLOCKDEV ]]; then
	echo "$EXIT_NOT_BLOCK_DEVICE" "$BLOCKDEV"
fi

(
	case "$(file "$IMAGE")" in
	*"XZ compressed"*)
		echo "Writing xz image..." >&2
		xzcat "$IMAGE"
		;;
	*"gzip compressed data"*)
		echo "Writing gz image..." >&2
		zcat "$IMAGE"
		;;
	*"Zip archive"*)
		echo "Writing zip image..." >&2
		unzip -p "$IMAGE"
		;;
	*"7-zip archive data"*)
		echo "Writing 7-zip image..." >&2
		7z e -so "$IMAGE"
		;;
	*"Zstandard compressed data"*)
		echo "Writing Zstd image..." >&2
		zstdcat "$IMAGE"
		;;
	*)
		echo "Writing raw image..." >&2
		cat "$IMAGE"
		;;
	esac
) | sudo dd "of=$BLOCKDEV" bs=16M status=progress
echo "Syncing block device..."
sudo sync "$BLOCKDEV"
echo "$IMAGE has been written to $BLOCKDEV."
