#!/usr/bin/env bash

find_target_distros() {
	local requested=() supported=() deb="$1" pkg_conf="$2"
	shift 2
	supported=("$@")

	local requested_json i
	for i in "$deb" "*"; do
		if requested_json="$(jq -er --arg target "$i" '
			to_entries[]
			| select(.key == $target
				or (.key != "*"
					and (.key as $k | $target | test($k))))
			| .value.Releases
		' "$pkg_conf")" && [[ $requested_json != "null" ]]; then
			mapfile -t requested < <(jq -er '.[]' <<<"$requested_json") && array_remove "requested" ""
			array_intersect "${supported[@]}" -- "${requested[@]}"
			return
		fi
	done

	if [[ $RSDK_OPTION_DEFAULT_DISTRO == "true" ]]; then
		echo "${supported[0]}"
	fi
}

gh_release_download() {
	local retry=3
	while ! gh release download --clobber "$tag" --repo "$org/$pkg" --dir "$RSDK_TEMP/$pkg" "$@"; do
		if ((retry-- <= 0)); then
			echo "Failed to download '$org/$pkg@$tag'." >&2
			return 2
		fi
		sleep 5
	done
}

gh_release_view() {
	local retry=3 filter="${1:-.assets[].name | select(endswith(\".deb\"))}" assets
	while ! assets="$(gh release view "$tag" --repo "$org/$pkg" --json assets --jq "$filter")"; do
		if ((retry-- <= 0)); then
			echo "Failed to view release '$org/$pkg@$tag'." >&2
			return 2
		fi
		sleep 5
	done
	echo "$assets"
}

download_pkgs() {
	local RSDK_TEMP i DISTROS=("$@") OUTPUT="$RSDK_OPTION_DEB_DIR"
	RSDK_TEMP="$(mktemp -d)"
	for i in "${DISTROS[@]}"; do
		mkdir -p "$OUTPUT/$i"
	done

	for i in "${!RSDK_PKG_REPO_ARRAY[@]}"; do
		request_parallel
		(
			org="$RSDK_PACKAGE_ORG"
			pkg="${RSDK_PKG_REPO_ARRAY[i]}"
			tag="${RSDK_PKG_REPO_TAG_ARRAY[i]}"

			echo "Downloading '$org/$pkg@$tag'..."
			mkdir -p "$RSDK_TEMP/$pkg"

			if [[ $RSDK_OPTION_DRY_RUN == "false" ]]; then
				local pkg_conf_blob
				pkg_conf_blob="$(gh_release_view '.assets[].name | select(. == "pkg.conf")')"
				if [[ -z $pkg_conf_blob ]]; then
					if [[ $RSDK_OPTION_DEFAULT_DISTRO == "true" ]]; then
						gh_release_download
						cp "$RSDK_TEMP/$pkg"/*.deb "$OUTPUT/${DISTROS[0]}"
					else
						echo "No pkg.conf found when policy requires explicit distro." >&2
					fi
				else
					gh_release_download -p "pkg.conf"
					if ! jq -er '"Syntax check"' "$RSDK_TEMP/$pkg/pkg.conf" >/dev/null; then
						echo "Invalid pkg.conf for '$org/$pkg@$tag', aborting." >&2
						return 1
					fi
					local assets_blob
					assets_blob="$(gh_release_view)"
					mapfile -t assets <<<"$assets_blob" && array_remove "assets" ""
					for j in "${assets[@]}"; do
						mapfile -t targets < <(find_target_distros "$j" "$RSDK_TEMP/$pkg/pkg.conf" "${DISTROS[@]}") && array_remove "targets" ""
						for k in "${targets[@]}"; do
							if [[ ! -f "$RSDK_TEMP/$pkg/$j" ]]; then
								gh_release_download -p "$j"
							fi
							cp "$RSDK_TEMP/$pkg/$j" "$OUTPUT/$k"
						done
					done
				fi
			fi
		) &
	done
	wait_parallel

	rm -rf "$RSDK_TEMP"
}

main() {
	local SCRIPT_DIR
	SCRIPT_DIR="$(dirname "$(realpath "$0")")"
	# shellcheck source=src/lib/rsdk/utils.sh
	source "$SCRIPT_DIR/../../lib/rsdk/utils.sh"
	# shellcheck source=src/lib/rsdk/stdlib.sh
	source "$SCRIPT_DIR/../../lib/rsdk/stdlib.sh"

	local TEMP
	if ! TEMP="$(getopt -o "hdv" -l "help,dry-run,deb-dir:,no-default-distro,verbose" -n "$0" -- "$@")"; then
		return
	fi
	eval set -- "$TEMP"

	export RSDK_OPTION_DRY_RUN="${RSDK_OPTION_DRY_RUN:-false}"
	export RSDK_OPTION_VERBOSE="${RSDK_OPTION_VERBOSE:-false}"
	export RSDK_PACKAGE_ORG="${RSDK_PACKAGE_ORG:-$("$SCRIPT_DIR/../../bin/rsdk" config infra.organizations.package)}"
	export RSDK_PKG_REPO_ARRAY=("${RSDK_PKG_REPO_ARRAY[@]}")
	export RSDK_PKG_REPO_TAG_ARRAY=("${RSDK_PKG_REPO_TAG_ARRAY[@]}")
	export RSDK_OPTION_DEB_DIR="${RSDK_OPTION_DEB_DIR:-${TMPDIR:-/tmp}/rsdk-deb}"
	export RSDK_OPTION_DEFAULT_DISTRO="${RSDK_OPTION_DEFAULT_DISTRO:-true}"

	if ! jq -er '"Syntax check"' pkgs.json >/dev/null; then
		echo "Invalid pkgs.json, aborting." >&2
		return 1
	fi
	mapfile -t RSDK_PKG_REPO_ARRAY < <(jq -er 'to_entries[].key' pkgs.json) && array_remove "RSDK_PKG_REPO_ARRAY" ""
	mapfile -t RSDK_PKG_REPO_TAG_ARRAY < <(jq -er 'to_entries[].value' pkgs.json) && array_remove "RSDK_PKG_REPO_TAG_ARRAY" ""

	while true; do
		TEMP="$1"
		shift
		case "$TEMP" in
		-d | --dry-run)
			RSDK_OPTION_DRY_RUN="true"
			;;
		-v | --verbose)
			RSDK_OPTION_VERBOSE="true"
			;;
		-h | --help)
			TEMP="$(basename "$0")"
			rsdk help "${TEMP#rsdk-}"
			return
			;;
		--deb-dir)
			RSDK_OPTION_DEB_DIR="$1"
			shift
			;;
		--no-default-distro)
			RSDK_OPTION_DEFAULT_DISTRO="false"
			;;
		--)
			break
			;;
		*)
			error "$EXIT_UNKNOWN_OPTION" "$TEMP"
			;;
		esac
	done

	if (($# == 0)); then
		"$0" --help
		return
	fi

	download_pkgs "$@"
}

main "$@"
