name: Build images

on:
  merge_group:
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '**.md'
      - .gitignore
      - 'docs/**'
      - 'theme/**'
      - 'po/**'
      - book.toml
      - .github/workflows/docs.yaml
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      products: ${{ steps.query.outputs.products }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Query available board configs
        id: query
        run: |
          echo "products=$(jq -c '. | map(.product)' src/share/rsdk/configs/products.json)" >> $GITHUB_OUTPUT
  build-images:
    needs: [ query ]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        products: ${{ fromJSON(needs.query.outputs.products) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build ${{ matrix.products }}
        uses: ./.github/actions/build
        with:
          product: ${{ matrix.products }}
          test-repo: true
          artifacts: true
